### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lautarobock**
change `moveend` to its real name `onMoveEnd`

### CODE REVIEW

**Comment by quentin-ol** [comment]
Thanks for catching this!
Not only ```moveend```  event needs a name change. I suggest that all events are correctly documented before merging. Could you correct the other events names ? If not, I should have a bit of spare time by the end of next week.

**Comment by lautarobock** [comment]
Yes, I realized too late :) I will change if a few minutes

**Comment by lautarobock** [comment]
done

**Comment by quentin-ol** [comment]
Thanks @lautarobock !

**Pull request merged**
