### PR TITLE
add id input to feature

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
This gives the possibility to set a features id. I need this for click events on the map to find out on what feature one clicked.

### CODE REVIEW

**Comment by quentin-ol** [comment]
Hey @FallenRiteMonk, could you change the type to string|number|undefined as Openlayers allows for non numeric IDs ?
Otherwise, seems good to me.

**Comment by FallenRiteMonk** [comment]
@quentin-ol Done!

**Comment by quentin-ol** [comment]
👍

**Comment by earosb** [comment]
> ... find out on what feature one clicked.
Hey @FallenRiteMonk How are you doing this? i can't work this out

**Comment by FallenRiteMonk** [comment]
@earosb This is what how I'm doing it:
```
  mapClick(event) {
const feature = this.map.instance.forEachFeatureAtPixel([event.offsetX, event.offsetY],
      function (feat) {
        return feat;
      });
    if (feature) {
      console.log(feature);
    } else {
      console.log("no feature");
    }
}
```

Normally one could pass ```event.pixel``` to the ```forEachFeatureAtPixel``` function, which would contain the pixels where the user clicked, but since I'm not casting the event to the ol event of the click I have to pass the array like this, since the default click event doesn't provide pixel. Still it works perfectly fine like this.

**Comment by vlahanas** [comment]
@FallenRiteMonk Have you managed to "Extract" the id of the clicked feature?

**Pull request merged**
