### PR TITLE
popup implementation

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
I started implementing the pupup feature I requested. 
As written in #33 I tried to implement it using the ol-popup library, but since it is not on npm I tried it using [this fork](https://github.com/ghettovoice/ol3-popup-umd) of the library.
Sadly I wasn't able of importing the library as it is, so I decided to stop and ask for help. Maybe @quentin-ol you could give it a short try and let me know, otherwise I'll re implement the library directly into this project.

Let me know what you found out/think, even if you would generally like me to recreate the popup as component of this project.

### CODE REVIEW

**Comment by FallenRiteMonk** [comment]
Finished implementing this feature by just translating the library. I think this is the most efficient way.

The only thing that is not working as expected is the two way binding of the 'show' variable of the popup element. Otherwise it works fine and I think it can be merged. 

@quentin-ol what do you think?

**Comment by achimha** [comment]
Shouldn't this be part of another library as it's not something offered by OL directly? There is `ol.Overlay` which can be easily used to style the popups in your own app. I have a working implementation of that and do my popups with a tiny bit of Angular markup.

**Comment by FallenRiteMonk** [comment]
@achimha I have never actually thought about that, but it's a decision @quentin-ol has to tackle!

@achimha could you provide me an example of you implementation? Some kind of minimal example or something, I'd really appreciate it!

**Comment by achimha** [comment]
I created a very simple popup, not flexible at all but maybe the basic idea can help. It looks like this, the white bubble with "EDVE" in it:

screen shot 2017-02-13 at 22 10 34

The markup (with my latest PR):

```
<aol-overlay>
    <aol-coordinate
        [x]="x"
        [y]="y"
        [srid]="'EPSG:4326'"
    ></aol-coordinate>
    <aol-content>
        <div class="ol-airport-popup">
            <div class="ol-airport-popup-content">
                <h1>&darr;{{ getWaypointName(xxx) }}</h1>
            </div>
        </div>
    </aol-content>
</aol-overlay>
```

And I style it like this in my component's SCSS:

```
    .ol-airport-popup {
        position: absolute;
        background-color: white;
        padding: 5px;
        border: 1px solid rgb(204, 204, 204);
        border-radius: 5px;
        bottom: 12px;
        left: -31px;

        &:after, &:before {
            top: 100%;
            border: solid transparent;
            content: " ";
            height: 0;
            width: 0;
            position: absolute;
            pointer-events: none;
        }

        &:before {
            border-top-color: #cccccc;
            border-width: 11px;
            left: 30px;
            margin-left: -11px;
        }

        &:after {
            border-top-color: white;
            border-width: 10px;
            left: 30px;
            margin-left: -10px;
        }

        &.marker {
            margin-bottom: 30px;
        }
    }

    .ol-airport-popup-content {
        max-height: 200px;
        overflow-x: auto;

        h1 {
            margin: 0;
            text-align: center;
            font-weight: bold;
            font-size: 16px;
        }
    }
```
A more powerful implementation can be done. I think this is a little bit beyond the scope of this project as it's an add-on to OL and there are a million ways to do it and to style it.

**Comment by FallenRiteMonk** [comment]
Thanks. I'll give it a try!

**Comment by quentinlampin** [comment]
Everyone, I'd like to know your opinion on this matter. 
To summarize the options: 

1. support Openlayers third-parties plugins. 
2. provide a drop-in replacements for those plugins.
3. let users implement their own (possibly using third-parties plugins).

- Solution 1. implies potential headaches on Openlayers/plugins new versions but provides easy and ready-to-use solutions for most use-cases.
- Solution 2. implies a lot of dev to match the features of said plugins but means an easier to maintain code-base.
- Solution 3. is the easiest solution for us but requires a bit more involvement on the user-side.

My preference goes to solution 3. 
IMO, most plugins are convenience toolboxes. In most cases, e.g. popup, users will want to customize/alter the behavior of said plugins. Ultimately, Solution 1. will create issues/feature-requests to match individual requirements which we won't be able to address (the plugin base-code is not ours). Moreover, if/when such a plugin goes unmaintained, we either have the choice to maintain it ourselve or drop the feature altogether :(.
Solution 2 seems unrealistic to me. Most of us (me included) work on this library as a side-project/hobby.

**Comment by quentin-ol** [comment]
Closing this for now. @achimha provided a clean/easy and dependencies-free solution to implement popups. This can still be re-opened if need be

**Pull request closed without merging**
