### PR TITLE
More sources and layers added

### PR DESCRIPTION
**Pull request by achimha**
Further cleanup, added .editorconfig
Added ol.format.MVT implementation
Added ol.layer.VectorTile implementation
Added ol.source.XYZ implementation
Added ol.source.VectorTile implementation
Added provider configuration to all source implementations so they can be injected as their SourceComponent base class
Added ol.tilegrid.TileGrid implementation

### CODE REVIEW

**Comment by achimha** [comment]
I've added a few more improvements to this PR, still mostly work in progress but improving the situation.

**Comment by quentinlampin** [comment]
Is there anything we need to work on before merging?

**Comment by achimha** [comment]
I am not aware of anything broken that wasn't broken/unfinished before. Sorry about the massive PR. Future ones should be smaller...

**Comment by quentinlampin** [comment]
Don't apologize! The size of the PR is justified by the extent of the work you've done. Much appreciated.
I will proceed with the merge. The npm package update will soon follow.

**Pull request merged**
