### PR TITLE
Add Icon style feature

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
can be used to add a custom icon to a point on the map
example in the README

I didn't test all the options explicitly, but there shouldn't be any problems.

### CODE REVIEW

**Comment by FallenRiteMonk** [comment]
This is the last feature I needed for my project so I would like to kindly ask you to do a npm publish so that I can start replacing my original implementation of ol in my project with this library!

Thanks and Greetings

**Comment by quentin-ol** [comment]
Seems good to me. 
Thank! 👍

**Comment by quentin-ol** [comment]
Available as a NPM package: version 0.3.0

**Comment by FallenRiteMonk** [comment]
great thanks

**Comment by FallenRiteMonk** [comment]
Sorry but it was not the last feature... totally forgot about click events!
I implemented all the events on a map element and made a PR for that #15

**Pull request merged**
